- name: Create a sandbox instance
  hosts: localhost
  gather_facts: True
  vars:
    keypair: demo-ps
    region: us-east-1
    instance_type: t2.micro
    id: "webapp"
    security_group: webapp-sec
    image: ami-052efd3df9dad4825

  tasks:
    - name: Get instances facts
      ec2_instance_facts:
          aws_access_key: "{{ec2_access_key}}"
          aws_secret_key: "{{ec2_secret_key}}"
          region: "{{ region }}"
      register: result

    - name: Instances ID
      debug:
          msg: "ID: {{ item.instance_id }} - State: {{ item.state.name }} - Public DNS: {{ item.public_dns_name }}"
      loop: "{{ result.instances }}"

    - name: Launch instance
      amazon.aws.ec2:
         aws_access_key: "{{ec2_access_key}}"
         aws_secret_key: "{{ec2_secret_key}}"
         key_name: "{{ keypair }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         count: 1
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      loop: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      delegate_to: "{{ item.public_dns_name }}"
      wait_for_connection:
        delay: 60
        timeout: 320
      loop: "{{ ec2.instances }}"

- name: Configure instance(s)
  hosts: launched
  become: True
  gather_facts: True
  tasks:
  - name: Installs Nginx web server
    apt:
      name: ['nginx']
      state: latest
  - name: Upload default index.html for host
    copy: 
      src: /root/AWS_Ansible/index.html 
      dest: /var/www/html/ 
      mode: 0644
  handlers:
    - name: start Nginx
      service: 
        name: nginx 
        state: started

